name: povo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  google_sign_in: ^6.2.2

  # State Management
  get: ^4.6.5

  # Camera
  camerawesome: ^2.1.0

  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  lottie: ^3.3.1
  shimmer: ^3.0.0

  # Utils
  image_picker: ^1.0.0
  image_cropper: ^9.0.0
  permission_handler: ^11.4.0
  path_provider: ^2.0.15
  uuid: ^4.5.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  flutter_image_compress: ^2.0.3
  url_launcher: ^6.1.12
  share_plus: ^10.1.4
  flutter_local_notifications: ^18.0.1

  # Animations
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
