name: povo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  firebase_messaging: ^14.6.3
  google_sign_in: ^6.2.2

  # State Management
  get: ^4.6.5

  # Camera
  camerawesome: ^2.1.0

  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  lottie: ^2.4.0
  shimmer: ^3.0.0

  # Utils
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  permission_handler: ^10.4.1
  path_provider: ^2.0.15
  uuid: ^4.5.1
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  flutter_image_compress: ^2.0.3
  url_launcher: ^6.1.12
  share_plus: ^7.0.2
  flutter_local_notifications: ^15.1.0+1

  # Animations
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
