// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tKTD89r2-LrY2unwVef0uiqgjEh83Hs',
    appId: '1:900906008940:web:34eb062adf8325de8f3349',
    messagingSenderId: '900906008940',
    projectId: 'povo-19101',
    authDomain: 'povo-19101.firebaseapp.com',
    storageBucket: 'povo-19101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWtLhygsjxC6aAvrlqMue3Gy8HmrMK4kA',
    appId: '1:900906008940:android:6024c31c4ba5f53e8f3349',
    messagingSenderId: '900906008940',
    projectId: 'povo-19101',
    storageBucket: 'povo-19101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv50y_S48NQ3bSztw4rfI5PHFDtX70vjU',
    appId: '1:900906008940:ios:6c0ffeda0f8fff868f3349',
    messagingSenderId: '900906008940',
    projectId: 'povo-19101',
    storageBucket: 'povo-19101.firebasestorage.app',
    iosBundleId: 'com.example.povo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv50y_S48NQ3bSztw4rfI5PHFDtX70vjU',
    appId: '1:900906008940:ios:6c0ffeda0f8fff868f3349',
    messagingSenderId: '900906008940',
    projectId: 'povo-19101',
    storageBucket: 'povo-19101.firebasestorage.app',
    iosBundleId: 'com.example.povo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4tKTD89r2-LrY2unwVef0uiqgjEh83Hs',
    appId: '1:900906008940:web:cd1e48e613765fd18f3349',
    messagingSenderId: '900906008940',
    projectId: 'povo-19101',
    authDomain: 'povo-19101.firebaseapp.com',
    storageBucket: 'povo-19101.firebasestorage.app',
  );
}
